on:
  push:
    branches:
      - master

name: Cross-compile

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: |
            target/x86_64-unknown-linux-gnu/release/lma

  build_windows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-pc-windows-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: |
            target/x86_64-pc-windows-gnu/release/lma.exe
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-pc-windows-gnu --features portable
      - uses: actions/upload-artifact@v3
        with:
          name: winportable
          path: |
            target/x86_64-pc-windows-gnu/release/lma.exe

  publish:
    name: Publish as a prerelease
    needs: [build_linux, build_windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Rename portable exe
        run: mv winportable/lma.exe winportable/lma-p.exe

      - name: Create a pre-release
        run: hub release create pre-release_${{github.run_number}} -p -m pre-release -a linux/lma#lma-linux -a windows/lma.exe#lma-windows -a winportable/lma-p.exe#lma-windows-portable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
