on: [push, pull_request]

name: Cross-compile

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: |
            target/x86_64-unknown-linux-gnu/release/lma
            
  build_windows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-pc-windows-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: |
            target/x86_64-pc-windows-gnu/release/lma.exe

  publish:
    name: Publish as a prerelease
    needs: [build_linux, build_windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: 'Create Release'
        run: hub release create ${{ github.ref }} -p -m Prerelease -a linux/lma#lma-linux -a windows/lma.exe#lma-windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
